[project]
name = "bio-cal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "lxml>=6.0.0",
    "pillow>=11.3.0",
    "pyvips[binary]>=3.0.0",
]
